services:
  - type: web
    name: burlington-arcade
    runtime: custom
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: JWT_SECRET
        scope: build,runtime
      - key: JWT_EXPIRATION
        value: "3600000"
        scope: runtime
      - key: JWT_REFRESH_EXPIRATION
        value: "86400000"
        scope: runtime
      - key: H2_CONSOLE_ENABLED
        value: "false"
        scope: runtime
